### ISSUE TITLE
Node labels

### ISSUE THREAD

**Issue by mdorr75** [Panda88CO/udi-TeslaPowerWall#1]
Hello.  Thanks for writing and sharing the Powerwall node server.  I just got a Powerwall a few months ago, so it's nice to now have it integrated into my ISY system.

If I may offer one suggestion for improvement: It appears that the data reported in the second and third columns of the info node (at least the fields with labels containing Today or Yesterday) refer to energy rather than power, whose units are probably kWh.  Hopefully the field labels and unit of measure (33 it appears from the developer's guide) are easy to change.

**Comment by Panda88CO** [comment]
Thanks – I am working on making the node server PGC compatible (will need to change the structure a little – will end up with 3 nodes – vs the 2 now).  I’ll include the fix with thisLet me know if you have other recommendationsChristian Sent from Mail for Windows 10 From: mdorr75Sent: Monday, July 5, 2021 1:46 PMTo: Panda88CO/udi-TeslaPowerWallCc: SubscribedSubject: [Panda88CO/udi-TeslaPowerWall] Node labels (#1) Hello. Thanks for writing and sharing the Powerwall node server. I just got a Powerwall a few months ago, so it's nice to now have it integrated into my ISY system.If I may offer one suggestion for improvement: It appears that the data reported in the second and third columns of the info node (at least the fields with labels containing Today or Yesterday) refer to energy rather than power, whose units are probably kWh. Hopefully the field labels and unit of measure (33 it appears from the developer's guide) are easy to change.—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by mdorr75** [comment]
I've been running the current version on PGC all day today, and it seems to be working fine.

**Comment by Panda88CO** [comment]
i know but it is getting PGC and non-PGC to work at the same time.

Christian Olgaard
________________________________

**Comment by mdorr75** [comment]
OK.  Thanks again for your efforts.

**Comment by Panda88CO** [comment]
I change uom to 33 but it still shows KW ☹.  Maybe I need to reboot ISY?   Sent from Mail for Windows 10 From: mdorr75Sent: Monday, July 5, 2021 10:21 PMTo: Panda88CO/udi-TeslaPowerWallCc: Panda88CO; CommentSubject: Re: [Panda88CO/udi-TeslaPowerWall] Node labels (#1) OK. Thanks again for your efforts.—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by mdorr75** [comment]
Sorry, I wish I could help.  You are already way more of an expert than I am, since you've actually created a node server whereas I've only looked at the developer's guide to try to get some understanding of how node servers work.  Some other node servers I've used provide an "Update profile" button that somehow updates the node server info in the ISY, but I suppose rebooting the ISY would do that too.  If not, and unless you have a better resource, maybe try posting to the UDI forum.

**Comment by Panda88CO** [comment]
ThanksI’ll take a look later – I believe the code is right now – and it may show correctly for new users  I did post a small update to the node serverChristian Sent from Mail for Windows 10 From: mdorr75Sent: Tuesday, July 6, 2021 10:12 PMTo: Panda88CO/udi-TeslaPowerWallCc: Panda88CO; CommentSubject: Re: [Panda88CO/udi-TeslaPowerWall] Node labels (#1) Sorry, I wish I could help. You are already way more of an expert than I am, since you've actually created a node server whereas I've only looked at the developer's guide to try to get some understanding of how node servers work. Some other node servers I've used provide an "Update profile" button that somehow updates the node server info in the ISY, but I suppose rebooting the ISY would do that too. If not, and unless you have a better resource, maybe try posting to the UDI forum.—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
